# Generated by Django 2.0.3 on 2018-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
